version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      isolated_nw:
    ports:
      - "81:80"
      - "22:22"
    restart: always
    container_name: nginx.local
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - ./public:/public
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php_browscap.ini:/usr/local/etc/php/php_browscap.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    networks:
      isolated_nw:
    container_name: php
    expose:
      - "9003"

  database:
    build:
      context: database_config
      dockerfile: Dockerfile
    image: mysql:5.7
    volumes:
      - ./database_folder:/var/lib/mysql
      - ./scripts:/scripts
      - ./database_config:/etc/mysql/
    networks:
      isolated_nw:
    ports:
      - 3306:3306
    env_file:
      - .env
    container_name: mysqld.conectala
    # command: "/scripts/config.sh"
    # entrypoint: ["/scripts/config.sh"]

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8282:80"
    env_file:
      - .env
    networks:
      isolated_nw:
    container_name: phpmyadmin

networks:
  isolated_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
          aux_addresses:
            database: 192.168.56.3
            nginx: 192.168.56.4
            php: 192.168.56.5
